name: Build and Deploy Docs

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Node.js and dependencies
      uses: actions/setup-node@v2
      with:
        node-version: '18.x'
    - run: npm install

    - name: Build and bundle JavaScript code
    - name: Install Ruby and Jekyll
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
    - name: Install Bundler
      run: |
        sudo gem install bundler
    - name: Install Jekyll dependencies
      run: |
        cd docs
        bundle config set path 'vendor/bundle'
        bundle install
    - name: Build Jekyll site
      run: |
        cd docs
        bundle exec jekyll build
  
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_site
        enable_jekyll: true
